/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole.impl;

import edu.upb.lp.isc.pole.Condicional;
import edu.upb.lp.isc.pole.CondicionalElseIf;
import edu.upb.lp.isc.pole.Expresion;
import edu.upb.lp.isc.pole.Instruccion;
import edu.upb.lp.isc.pole.PolePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Condicional</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.impl.CondicionalImpl#getExpr <em>Expr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.CondicionalImpl#getInstr <em>Instr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.CondicionalImpl#getCasiTeam <em>Casi Team</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.CondicionalImpl#getInstrElse <em>Instr Else</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CondicionalImpl extends InstruccionImpl implements Condicional
{
  /**
   * The cached value of the '{@link #getExpr() <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr()
   * @generated
   * @ordered
   */
  protected Expresion expr;

  /**
   * The cached value of the '{@link #getInstr() <em>Instr</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstr()
   * @generated
   * @ordered
   */
  protected EList<Instruccion> instr;

  /**
   * The cached value of the '{@link #getCasiTeam() <em>Casi Team</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCasiTeam()
   * @generated
   * @ordered
   */
  protected EList<CondicionalElseIf> casiTeam;

  /**
   * The cached value of the '{@link #getInstrElse() <em>Instr Else</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstrElse()
   * @generated
   * @ordered
   */
  protected EList<Instruccion> instrElse;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CondicionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PolePackage.Literals.CONDICIONAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getExpr()
  {
    return expr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr(Expresion newExpr, NotificationChain msgs)
  {
    Expresion oldExpr = expr;
    expr = newExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PolePackage.CONDICIONAL__EXPR, oldExpr, newExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpr(Expresion newExpr)
  {
    if (newExpr != expr)
    {
      NotificationChain msgs = null;
      if (expr != null)
        msgs = ((InternalEObject)expr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PolePackage.CONDICIONAL__EXPR, null, msgs);
      if (newExpr != null)
        msgs = ((InternalEObject)newExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PolePackage.CONDICIONAL__EXPR, null, msgs);
      msgs = basicSetExpr(newExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PolePackage.CONDICIONAL__EXPR, newExpr, newExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instruccion> getInstr()
  {
    if (instr == null)
    {
      instr = new EObjectContainmentEList<Instruccion>(Instruccion.class, this, PolePackage.CONDICIONAL__INSTR);
    }
    return instr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CondicionalElseIf> getCasiTeam()
  {
    if (casiTeam == null)
    {
      casiTeam = new EObjectContainmentEList<CondicionalElseIf>(CondicionalElseIf.class, this, PolePackage.CONDICIONAL__CASI_TEAM);
    }
    return casiTeam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instruccion> getInstrElse()
  {
    if (instrElse == null)
    {
      instrElse = new EObjectContainmentEList<Instruccion>(Instruccion.class, this, PolePackage.CONDICIONAL__INSTR_ELSE);
    }
    return instrElse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PolePackage.CONDICIONAL__EXPR:
        return basicSetExpr(null, msgs);
      case PolePackage.CONDICIONAL__INSTR:
        return ((InternalEList<?>)getInstr()).basicRemove(otherEnd, msgs);
      case PolePackage.CONDICIONAL__CASI_TEAM:
        return ((InternalEList<?>)getCasiTeam()).basicRemove(otherEnd, msgs);
      case PolePackage.CONDICIONAL__INSTR_ELSE:
        return ((InternalEList<?>)getInstrElse()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PolePackage.CONDICIONAL__EXPR:
        return getExpr();
      case PolePackage.CONDICIONAL__INSTR:
        return getInstr();
      case PolePackage.CONDICIONAL__CASI_TEAM:
        return getCasiTeam();
      case PolePackage.CONDICIONAL__INSTR_ELSE:
        return getInstrElse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PolePackage.CONDICIONAL__EXPR:
        setExpr((Expresion)newValue);
        return;
      case PolePackage.CONDICIONAL__INSTR:
        getInstr().clear();
        getInstr().addAll((Collection<? extends Instruccion>)newValue);
        return;
      case PolePackage.CONDICIONAL__CASI_TEAM:
        getCasiTeam().clear();
        getCasiTeam().addAll((Collection<? extends CondicionalElseIf>)newValue);
        return;
      case PolePackage.CONDICIONAL__INSTR_ELSE:
        getInstrElse().clear();
        getInstrElse().addAll((Collection<? extends Instruccion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PolePackage.CONDICIONAL__EXPR:
        setExpr((Expresion)null);
        return;
      case PolePackage.CONDICIONAL__INSTR:
        getInstr().clear();
        return;
      case PolePackage.CONDICIONAL__CASI_TEAM:
        getCasiTeam().clear();
        return;
      case PolePackage.CONDICIONAL__INSTR_ELSE:
        getInstrElse().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PolePackage.CONDICIONAL__EXPR:
        return expr != null;
      case PolePackage.CONDICIONAL__INSTR:
        return instr != null && !instr.isEmpty();
      case PolePackage.CONDICIONAL__CASI_TEAM:
        return casiTeam != null && !casiTeam.isEmpty();
      case PolePackage.CONDICIONAL__INSTR_ELSE:
        return instrElse != null && !instrElse.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CondicionalImpl
