/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole.impl;

import edu.upb.lp.isc.pole.ExpresionBooleana;
import edu.upb.lp.isc.pole.PolePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expresion Booleana</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpresionBooleanaImpl extends ExpresionImpl implements ExpresionBooleana
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpresionBooleanaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PolePackage.Literals.EXPRESION_BOOLEANA;
  }

} //ExpresionBooleanaImpl
