/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole.impl;

import edu.upb.lp.isc.pole.ExpresionOperacionesBooleanas;
import edu.upb.lp.isc.pole.PolePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expresion Operaciones Booleanas</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpresionOperacionesBooleanasImpl extends ExpresionBooleanaImpl implements ExpresionOperacionesBooleanas
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpresionOperacionesBooleanasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PolePackage.Literals.EXPRESION_OPERACIONES_BOOLEANAS;
  }

} //ExpresionOperacionesBooleanasImpl
