/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole.impl;

import edu.upb.lp.isc.pole.DeclVariables;
import edu.upb.lp.isc.pole.Expresion;
import edu.upb.lp.isc.pole.Funciones;
import edu.upb.lp.isc.pole.Instruccion;
import edu.upb.lp.isc.pole.PolePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Funciones</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.impl.FuncionesImpl#getTipoDeDato <em>Tipo De Dato</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.FuncionesImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.FuncionesImpl#getParam <em>Param</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.FuncionesImpl#getInstr <em>Instr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.FuncionesImpl#getE <em>E</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FuncionesImpl extends InstruccionImpl implements Funciones
{
  /**
   * The default value of the '{@link #getTipoDeDato() <em>Tipo De Dato</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoDeDato()
   * @generated
   * @ordered
   */
  protected static final String TIPO_DE_DATO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoDeDato() <em>Tipo De Dato</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoDeDato()
   * @generated
   * @ordered
   */
  protected String tipoDeDato = TIPO_DE_DATO_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParam() <em>Param</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParam()
   * @generated
   * @ordered
   */
  protected EList<DeclVariables> param;

  /**
   * The cached value of the '{@link #getInstr() <em>Instr</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstr()
   * @generated
   * @ordered
   */
  protected EList<Instruccion> instr;

  /**
   * The cached value of the '{@link #getE() <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getE()
   * @generated
   * @ordered
   */
  protected Expresion e;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncionesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PolePackage.Literals.FUNCIONES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoDeDato()
  {
    return tipoDeDato;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoDeDato(String newTipoDeDato)
  {
    String oldTipoDeDato = tipoDeDato;
    tipoDeDato = newTipoDeDato;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PolePackage.FUNCIONES__TIPO_DE_DATO, oldTipoDeDato, tipoDeDato));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PolePackage.FUNCIONES__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DeclVariables> getParam()
  {
    if (param == null)
    {
      param = new EObjectContainmentEList<DeclVariables>(DeclVariables.class, this, PolePackage.FUNCIONES__PARAM);
    }
    return param;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instruccion> getInstr()
  {
    if (instr == null)
    {
      instr = new EObjectContainmentEList<Instruccion>(Instruccion.class, this, PolePackage.FUNCIONES__INSTR);
    }
    return instr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getE()
  {
    return e;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetE(Expresion newE, NotificationChain msgs)
  {
    Expresion oldE = e;
    e = newE;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PolePackage.FUNCIONES__E, oldE, newE);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setE(Expresion newE)
  {
    if (newE != e)
    {
      NotificationChain msgs = null;
      if (e != null)
        msgs = ((InternalEObject)e).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PolePackage.FUNCIONES__E, null, msgs);
      if (newE != null)
        msgs = ((InternalEObject)newE).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PolePackage.FUNCIONES__E, null, msgs);
      msgs = basicSetE(newE, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PolePackage.FUNCIONES__E, newE, newE));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PolePackage.FUNCIONES__PARAM:
        return ((InternalEList<?>)getParam()).basicRemove(otherEnd, msgs);
      case PolePackage.FUNCIONES__INSTR:
        return ((InternalEList<?>)getInstr()).basicRemove(otherEnd, msgs);
      case PolePackage.FUNCIONES__E:
        return basicSetE(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PolePackage.FUNCIONES__TIPO_DE_DATO:
        return getTipoDeDato();
      case PolePackage.FUNCIONES__NAME:
        return getName();
      case PolePackage.FUNCIONES__PARAM:
        return getParam();
      case PolePackage.FUNCIONES__INSTR:
        return getInstr();
      case PolePackage.FUNCIONES__E:
        return getE();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PolePackage.FUNCIONES__TIPO_DE_DATO:
        setTipoDeDato((String)newValue);
        return;
      case PolePackage.FUNCIONES__NAME:
        setName((String)newValue);
        return;
      case PolePackage.FUNCIONES__PARAM:
        getParam().clear();
        getParam().addAll((Collection<? extends DeclVariables>)newValue);
        return;
      case PolePackage.FUNCIONES__INSTR:
        getInstr().clear();
        getInstr().addAll((Collection<? extends Instruccion>)newValue);
        return;
      case PolePackage.FUNCIONES__E:
        setE((Expresion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PolePackage.FUNCIONES__TIPO_DE_DATO:
        setTipoDeDato(TIPO_DE_DATO_EDEFAULT);
        return;
      case PolePackage.FUNCIONES__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PolePackage.FUNCIONES__PARAM:
        getParam().clear();
        return;
      case PolePackage.FUNCIONES__INSTR:
        getInstr().clear();
        return;
      case PolePackage.FUNCIONES__E:
        setE((Expresion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PolePackage.FUNCIONES__TIPO_DE_DATO:
        return TIPO_DE_DATO_EDEFAULT == null ? tipoDeDato != null : !TIPO_DE_DATO_EDEFAULT.equals(tipoDeDato);
      case PolePackage.FUNCIONES__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PolePackage.FUNCIONES__PARAM:
        return param != null && !param.isEmpty();
      case PolePackage.FUNCIONES__INSTR:
        return instr != null && !instr.isEmpty();
      case PolePackage.FUNCIONES__E:
        return e != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tipoDeDato: ");
    result.append(tipoDeDato);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //FuncionesImpl
