/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole.impl;

import edu.upb.lp.isc.pole.Expresion;
import edu.upb.lp.isc.pole.ImprimirSinSaltoDeLinea;
import edu.upb.lp.isc.pole.PolePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Imprimir Sin Salto De Linea</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.impl.ImprimirSinSaltoDeLineaImpl#getE <em>E</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.impl.ImprimirSinSaltoDeLineaImpl#getE1 <em>E1</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ImprimirSinSaltoDeLineaImpl extends InstruccionImpl implements ImprimirSinSaltoDeLinea
{
  /**
   * The cached value of the '{@link #getE() <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getE()
   * @generated
   * @ordered
   */
  protected Expresion e;

  /**
   * The cached value of the '{@link #getE1() <em>E1</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getE1()
   * @generated
   * @ordered
   */
  protected EList<Expresion> e1;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImprimirSinSaltoDeLineaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PolePackage.Literals.IMPRIMIR_SIN_SALTO_DE_LINEA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getE()
  {
    return e;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetE(Expresion newE, NotificationChain msgs)
  {
    Expresion oldE = e;
    e = newE;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E, oldE, newE);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setE(Expresion newE)
  {
    if (newE != e)
    {
      NotificationChain msgs = null;
      if (e != null)
        msgs = ((InternalEObject)e).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E, null, msgs);
      if (newE != null)
        msgs = ((InternalEObject)newE).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E, null, msgs);
      msgs = basicSetE(newE, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E, newE, newE));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expresion> getE1()
  {
    if (e1 == null)
    {
      e1 = new EObjectContainmentEList<Expresion>(Expresion.class, this, PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E1);
    }
    return e1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E:
        return basicSetE(null, msgs);
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E1:
        return ((InternalEList<?>)getE1()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E:
        return getE();
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E1:
        return getE1();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E:
        setE((Expresion)newValue);
        return;
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E1:
        getE1().clear();
        getE1().addAll((Collection<? extends Expresion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E:
        setE((Expresion)null);
        return;
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E1:
        getE1().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E:
        return e != null;
      case PolePackage.IMPRIMIR_SIN_SALTO_DE_LINEA__E1:
        return e1 != null && !e1.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ImprimirSinSaltoDeLineaImpl
