/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole.impl;

import edu.upb.lp.isc.pole.Multiplicacion;
import edu.upb.lp.isc.pole.PolePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multiplicacion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MultiplicacionImpl extends ExpresionAritmeticaImpl implements Multiplicacion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiplicacionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PolePackage.Literals.MULTIPLICACION;
  }

} //MultiplicacionImpl
