/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.upb.lp.isc.PoleRuntimeModule;
import edu.upb.lp.isc.PoleStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PoleIdeSetup extends PoleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PoleRuntimeModule(), new PoleIdeModule()));
	}
	
}
