/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.serializer;

import com.google.inject.Inject;
import edu.upb.lp.isc.services.PoleGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class PoleSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PoleGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Condicional_NOTEAMKeyword_5_0_q;
	protected AbstractElementAlias match_ExpresionSimpleXokas_EKeyword_3_0_0_or_EKeyword_3_0_1;
	protected AbstractElementAlias match_ExpresionSimpleXokas_HyphenMinusKeyword_3_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PoleGrammarAccess) access;
		match_Condicional_NOTEAMKeyword_5_0_q = new TokenAlias(false, true, grammarAccess.getCondicionalAccess().getNOTEAMKeyword_5_0());
		match_ExpresionSimpleXokas_EKeyword_3_0_0_or_EKeyword_3_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getExpresionSimpleXokasAccess().getEKeyword_3_0_0()), new TokenAlias(false, false, grammarAccess.getExpresionSimpleXokasAccess().getEKeyword_3_0_1()));
		match_ExpresionSimpleXokas_HyphenMinusKeyword_3_1_q = new TokenAlias(false, true, grammarAccess.getExpresionSimpleXokasAccess().getHyphenMinusKeyword_3_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Condicional_NOTEAMKeyword_5_0_q.equals(syntax))
				emit_Condicional_NOTEAMKeyword_5_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExpresionSimpleXokas_EKeyword_3_0_0_or_EKeyword_3_0_1.equals(syntax))
				emit_ExpresionSimpleXokas_EKeyword_3_0_0_or_EKeyword_3_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExpresionSimpleXokas_HyphenMinusKeyword_3_1_q.equals(syntax))
				emit_ExpresionSimpleXokas_HyphenMinusKeyword_3_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'NOTEAM'?
	 *
	 * This ambiguous syntax occurs at:
	 *     casiTeam+=CondicionalElseIf (ambiguity) 'EZ' (rule end)
	 *     expr=Expresion 'WITHTEAM' (ambiguity) 'EZ' (rule end)
	 *     instr+=Instruccion (ambiguity) 'EZ' (rule end)
	 */
	protected void emit_Condicional_NOTEAMKeyword_5_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'e' | 'E'
	 *
	 * This ambiguous syntax occurs at:
	 *     y=INT (ambiguity) '-'? z=INT
	 */
	protected void emit_ExpresionSimpleXokas_EKeyword_3_0_0_or_EKeyword_3_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     y=INT ('e' | 'E') (ambiguity) z=INT
	 */
	protected void emit_ExpresionSimpleXokas_HyphenMinusKeyword_3_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
