/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asignacion Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.AsignacionVariable#getVariable <em>Variable</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.AsignacionVariable#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getAsignacionVariable()
 * @model
 * @generated
 */
public interface AsignacionVariable extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(DeclVariables)
   * @see edu.upb.lp.isc.pole.PolePackage#getAsignacionVariable_Variable()
   * @model
   * @generated
   */
  DeclVariables getVariable();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.AsignacionVariable#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(DeclVariables value);

  /**
   * Returns the value of the '<em><b>Valor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' containment reference.
   * @see #setValor(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getAsignacionVariable_Valor()
   * @model containment="true"
   * @generated
   */
  Expresion getValor();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.AsignacionVariable#getValor <em>Valor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' containment reference.
   * @see #getValor()
   * @generated
   */
  void setValor(Expresion value);

} // AsignacionVariable
