/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condicional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.Condicional#getExpr <em>Expr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.Condicional#getInstr <em>Instr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.Condicional#getCasiTeam <em>Casi Team</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.Condicional#getInstrElse <em>Instr Else</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getCondicional()
 * @model
 * @generated
 */
public interface Condicional extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getCondicional_Expr()
   * @model containment="true"
   * @generated
   */
  Expresion getExpr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.Condicional#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expresion value);

  /**
   * Returns the value of the '<em><b>Instr</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instr</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getCondicional_Instr()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstr();

  /**
   * Returns the value of the '<em><b>Casi Team</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.CondicionalElseIf}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Casi Team</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getCondicional_CasiTeam()
   * @model containment="true"
   * @generated
   */
  EList<CondicionalElseIf> getCasiTeam();

  /**
   * Returns the value of the '<em><b>Instr Else</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instr Else</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getCondicional_InstrElse()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstrElse();

} // Condicional
