/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Do While</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.DoWhile#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.DoWhile#getInstr <em>Instr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.DoWhile#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getDoWhile()
 * @model
 * @generated
 */
public interface DoWhile extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.upb.lp.isc.pole.PolePackage#getDoWhile_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.DoWhile#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Instr</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instr</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getDoWhile_Instr()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstr();

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getDoWhile_Expr()
   * @model containment="true"
   * @generated
   */
  Expresion getExpr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.DoWhile#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expresion value);

} // DoWhile
