/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionAritmetica#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getExpresionAritmetica()
 * @model
 * @generated
 */
public interface ExpresionAritmetica extends ExpresionDecimal
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(Operacion)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionAritmetica_Op()
   * @model containment="true"
   * @generated
   */
  Operacion getOp();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionAritmetica#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(Operacion value);

} // ExpresionAritmetica
