/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Booleana Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionBooleanaSimple#getX <em>X</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getExpresionBooleanaSimple()
 * @model
 * @generated
 */
public interface ExpresionBooleanaSimple extends ExpresionBooleana
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(String)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionBooleanaSimple_X()
   * @model
   * @generated
   */
  String getX();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionBooleanaSimple#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(String value);

} // ExpresionBooleanaSimple
