/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Simple Xokas</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionSimpleXokas#getX <em>X</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionSimpleXokas#getY <em>Y</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionSimpleXokas#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getExpresionSimpleXokas()
 * @model
 * @generated
 */
public interface ExpresionSimpleXokas extends ExpresionDecimal
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionSimpleXokas_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionSimpleXokas#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionSimpleXokas_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionSimpleXokas#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' attribute.
   * @see #setZ(int)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionSimpleXokas_Z()
   * @model
   * @generated
   */
  int getZ();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionSimpleXokas#getZ <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Z</em>' attribute.
   * @see #getZ()
   * @generated
   */
  void setZ(int value);

} // ExpresionSimpleXokas
