/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Simple Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionSimpleAritmetica#getX <em>X</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getExpresionSimpleAritmetica()
 * @model
 * @generated
 */
public interface ExpresionSimpleAritmetica extends ExpresionDecimal
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionSimpleAritmetica_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionSimpleAritmetica#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

} // ExpresionSimpleAritmetica
