/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Decimal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getExpresionDecimal()
 * @model
 * @generated
 */
public interface ExpresionDecimal extends Expresion
{
} // ExpresionDecimal
