/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion Negativo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.ExpresionNegativo#getE <em>E</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getExpresionNegativo()
 * @model
 * @generated
 */
public interface ExpresionNegativo extends ExpresionDecimal
{
  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getExpresionNegativo_E()
   * @model containment="true"
   * @generated
   */
  Expresion getE();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.ExpresionNegativo#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(Expresion value);

} // ExpresionNegativo
