/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.For#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.For#getVar <em>Var</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.For#getExpr <em>Expr</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.For#getAsig <em>Asig</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.For#getInstr <em>Instr</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getFor()
 * @model
 * @generated
 */
public interface For extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.upb.lp.isc.pole.PolePackage#getFor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.For#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(DeclVariables)
   * @see edu.upb.lp.isc.pole.PolePackage#getFor_Var()
   * @model containment="true"
   * @generated
   */
  DeclVariables getVar();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.For#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(DeclVariables value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(ExpresionBooleana)
   * @see edu.upb.lp.isc.pole.PolePackage#getFor_Expr()
   * @model containment="true"
   * @generated
   */
  ExpresionBooleana getExpr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.For#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(ExpresionBooleana value);

  /**
   * Returns the value of the '<em><b>Asig</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asig</em>' containment reference.
   * @see #setAsig(AsignacionVariable)
   * @see edu.upb.lp.isc.pole.PolePackage#getFor_Asig()
   * @model containment="true"
   * @generated
   */
  AsignacionVariable getAsig();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.For#getAsig <em>Asig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asig</em>' containment reference.
   * @see #getAsig()
   * @generated
   */
  void setAsig(AsignacionVariable value);

  /**
   * Returns the value of the '<em><b>Instr</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instr</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getFor_Instr()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstr();

} // For
