/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imprimir</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.Imprimir#getE <em>E</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.Imprimir#getE1 <em>E1</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getImprimir()
 * @model
 * @generated
 */
public interface Imprimir extends Instruccion
{
  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getImprimir_E()
   * @model containment="true"
   * @generated
   */
  Expresion getE();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.Imprimir#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(Expresion value);

  /**
   * Returns the value of the '<em><b>E1</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E1</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getImprimir_E1()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getE1();

} // Imprimir
