/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Llamado Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.LlamadoVariable#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoVariable()
 * @model
 * @generated
 */
public interface LlamadoVariable extends Expresion
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(DeclVariables)
   * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoVariable_Variable()
   * @model
   * @generated
   */
  DeclVariables getVariable();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.LlamadoVariable#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(DeclVariables value);

} // LlamadoVariable
