/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Llamado Funcion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.LlamadoFuncion#getFunc <em>Func</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.LlamadoFuncion#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoFuncion()
 * @model
 * @generated
 */
public interface LlamadoFuncion extends Expresion
{
  /**
   * Returns the value of the '<em><b>Func</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' reference.
   * @see #setFunc(Funciones)
   * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoFuncion_Func()
   * @model
   * @generated
   */
  Funciones getFunc();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.LlamadoFuncion#getFunc <em>Func</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' reference.
   * @see #getFunc()
   * @generated
   */
  void setFunc(Funciones value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoFuncion_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getArgs();

} // LlamadoFuncion
