/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Llamado Metodo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.LlamadoMetodo#getMethod <em>Method</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.LlamadoMetodo#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoMetodo()
 * @model
 * @generated
 */
public interface LlamadoMetodo extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Method</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' reference.
   * @see #setMethod(Funciones)
   * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoMetodo_Method()
   * @model
   * @generated
   */
  Funciones getMethod();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.LlamadoMetodo#getMethod <em>Method</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' reference.
   * @see #getMethod()
   * @generated
   */
  void setMethod(Funciones value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getLlamadoMetodo_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getArgs();

} // LlamadoMetodo
