/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Op Comp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.OpComp#getIzq <em>Izq</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.OpComp#getDer <em>Der</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getOpComp()
 * @model
 * @generated
 */
public interface OpComp extends EObject
{
  /**
   * Returns the value of the '<em><b>Izq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Izq</em>' containment reference.
   * @see #setIzq(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getOpComp_Izq()
   * @model containment="true"
   * @generated
   */
  Expresion getIzq();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.OpComp#getIzq <em>Izq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Izq</em>' containment reference.
   * @see #getIzq()
   * @generated
   */
  void setIzq(Expresion value);

  /**
   * Returns the value of the '<em><b>Der</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Der</em>' containment reference.
   * @see #setDer(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getOpComp_Der()
   * @model containment="true"
   * @generated
   */
  Expresion getDer();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.OpComp#getDer <em>Der</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Der</em>' containment reference.
   * @see #getDer()
   * @generated
   */
  void setDer(Expresion value);

} // OpComp
