/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operaciones Booleanas De Comparacion Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.OperacionesBooleanasDeComparacionAritmetica#getX <em>X</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.OperacionesBooleanasDeComparacionAritmetica#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getOperacionesBooleanasDeComparacionAritmetica()
 * @model
 * @generated
 */
public interface OperacionesBooleanasDeComparacionAritmetica extends ExpresionOperacionesBooleanas
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(String)
   * @see edu.upb.lp.isc.pole.PolePackage#getOperacionesBooleanasDeComparacionAritmetica_X()
   * @model
   * @generated
   */
  String getX();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.OperacionesBooleanasDeComparacionAritmetica#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(String value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(OpComp)
   * @see edu.upb.lp.isc.pole.PolePackage#getOperacionesBooleanasDeComparacionAritmetica_Op()
   * @model containment="true"
   * @generated
   */
  OpComp getOp();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.OperacionesBooleanasDeComparacionAritmetica#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(OpComp value);

} // OperacionesBooleanasDeComparacionAritmetica
