/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Op NEG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.OpNEG#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getOpNEG()
 * @model
 * @generated
 */
public interface OpNEG extends ExpresionOperacionesBooleanas
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expresion)
   * @see edu.upb.lp.isc.pole.PolePackage#getOpNEG_Expr()
   * @model containment="true"
   * @generated
   */
  Expresion getExpr();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.OpNEG#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expresion value);

} // OpNEG
