/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.pole.PolePackage
 * @generated
 */
public interface PoleFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PoleFactory eINSTANCE = edu.upb.lp.isc.pole.impl.PoleFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Programa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Programa</em>'.
   * @generated
   */
  Programa createPrograma();

  /**
   * Returns a new object of class '<em>Ejecucion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ejecucion</em>'.
   * @generated
   */
  Ejecucion createEjecucion();

  /**
   * Returns a new object of class '<em>Instruccion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruccion</em>'.
   * @generated
   */
  Instruccion createInstruccion();

  /**
   * Returns a new object of class '<em>Llamado Metodo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llamado Metodo</em>'.
   * @generated
   */
  LlamadoMetodo createLlamadoMetodo();

  /**
   * Returns a new object of class '<em>Funciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funciones</em>'.
   * @generated
   */
  Funciones createFunciones();

  /**
   * Returns a new object of class '<em>Imprimir</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imprimir</em>'.
   * @generated
   */
  Imprimir createImprimir();

  /**
   * Returns a new object of class '<em>Imprimir Sin Salto De Linea</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imprimir Sin Salto De Linea</em>'.
   * @generated
   */
  ImprimirSinSaltoDeLinea createImprimirSinSaltoDeLinea();

  /**
   * Returns a new object of class '<em>Condicional</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condicional</em>'.
   * @generated
   */
  Condicional createCondicional();

  /**
   * Returns a new object of class '<em>Condicional Else If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condicional Else If</em>'.
   * @generated
   */
  CondicionalElseIf createCondicionalElseIf();

  /**
   * Returns a new object of class '<em>Switch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Switch</em>'.
   * @generated
   */
  Switch createSwitch();

  /**
   * Returns a new object of class '<em>Case Switch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Case Switch</em>'.
   * @generated
   */
  CaseSwitch createCaseSwitch();

  /**
   * Returns a new object of class '<em>For</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>For</em>'.
   * @generated
   */
  For createFor();

  /**
   * Returns a new object of class '<em>While</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>While</em>'.
   * @generated
   */
  While createWhile();

  /**
   * Returns a new object of class '<em>Do While</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Do While</em>'.
   * @generated
   */
  DoWhile createDoWhile();

  /**
   * Returns a new object of class '<em>Decl Variables</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decl Variables</em>'.
   * @generated
   */
  DeclVariables createDeclVariables();

  /**
   * Returns a new object of class '<em>Asignacion Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asignacion Variable</em>'.
   * @generated
   */
  AsignacionVariable createAsignacionVariable();

  /**
   * Returns a new object of class '<em>Expresion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion</em>'.
   * @generated
   */
  Expresion createExpresion();

  /**
   * Returns a new object of class '<em>Llamado Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llamado Variable</em>'.
   * @generated
   */
  LlamadoVariable createLlamadoVariable();

  /**
   * Returns a new object of class '<em>Llamado Funcion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llamado Funcion</em>'.
   * @generated
   */
  LlamadoFuncion createLlamadoFuncion();

  /**
   * Returns a new object of class '<em>Expresion Decimal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Decimal</em>'.
   * @generated
   */
  ExpresionDecimal createExpresionDecimal();

  /**
   * Returns a new object of class '<em>Expresion Negativo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Negativo</em>'.
   * @generated
   */
  ExpresionNegativo createExpresionNegativo();

  /**
   * Returns a new object of class '<em>Expresion Simple Xokas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Simple Xokas</em>'.
   * @generated
   */
  ExpresionSimpleXokas createExpresionSimpleXokas();

  /**
   * Returns a new object of class '<em>Expresion Simple Aritmetica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Simple Aritmetica</em>'.
   * @generated
   */
  ExpresionSimpleAritmetica createExpresionSimpleAritmetica();

  /**
   * Returns a new object of class '<em>Expresion Longitud String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Longitud String</em>'.
   * @generated
   */
  ExpresionLongitudString createExpresionLongitudString();

  /**
   * Returns a new object of class '<em>Expresion Aritmetica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Aritmetica</em>'.
   * @generated
   */
  ExpresionAritmetica createExpresionAritmetica();

  /**
   * Returns a new object of class '<em>Suma</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Suma</em>'.
   * @generated
   */
  Suma createSuma();

  /**
   * Returns a new object of class '<em>Resta</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resta</em>'.
   * @generated
   */
  Resta createResta();

  /**
   * Returns a new object of class '<em>Multiplicacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplicacion</em>'.
   * @generated
   */
  Multiplicacion createMultiplicacion();

  /**
   * Returns a new object of class '<em>Division</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Division</em>'.
   * @generated
   */
  Division createDivision();

  /**
   * Returns a new object of class '<em>Modulo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modulo</em>'.
   * @generated
   */
  Modulo createModulo();

  /**
   * Returns a new object of class '<em>Operacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operacion</em>'.
   * @generated
   */
  Operacion createOperacion();

  /**
   * Returns a new object of class '<em>Expresion String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion String</em>'.
   * @generated
   */
  ExpresionString createExpresionString();

  /**
   * Returns a new object of class '<em>Expresion Simple String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Simple String</em>'.
   * @generated
   */
  ExpresionSimpleString createExpresionSimpleString();

  /**
   * Returns a new object of class '<em>Expresion Concatenacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Concatenacion</em>'.
   * @generated
   */
  ExpresionConcatenacion createExpresionConcatenacion();

  /**
   * Returns a new object of class '<em>Expresion Booleana</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Booleana</em>'.
   * @generated
   */
  ExpresionBooleana createExpresionBooleana();

  /**
   * Returns a new object of class '<em>Expresion Operaciones Booleanas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Operaciones Booleanas</em>'.
   * @generated
   */
  ExpresionOperacionesBooleanas createExpresionOperacionesBooleanas();

  /**
   * Returns a new object of class '<em>Operaciones Booleanas De Comparacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operaciones Booleanas De Comparacion</em>'.
   * @generated
   */
  OperacionesBooleanasDeComparacion createOperacionesBooleanasDeComparacion();

  /**
   * Returns a new object of class '<em>Expresion String Vacio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion String Vacio</em>'.
   * @generated
   */
  ExpresionStringVacio createExpresionStringVacio();

  /**
   * Returns a new object of class '<em>Operadores Logicos Booleanos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operadores Logicos Booleanos</em>'.
   * @generated
   */
  OperadoresLogicosBooleanos createOperadoresLogicosBooleanos();

  /**
   * Returns a new object of class '<em>Operaciones Booleanas De Comparacion Aritmetica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operaciones Booleanas De Comparacion Aritmetica</em>'.
   * @generated
   */
  OperacionesBooleanasDeComparacionAritmetica createOperacionesBooleanasDeComparacionAritmetica();

  /**
   * Returns a new object of class '<em>Op NEG</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op NEG</em>'.
   * @generated
   */
  OpNEG createOpNEG();

  /**
   * Returns a new object of class '<em>Op Comp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Op Comp</em>'.
   * @generated
   */
  OpComp createOpComp();

  /**
   * Returns a new object of class '<em>Expresion Booleana Simple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion Booleana Simple</em>'.
   * @generated
   */
  ExpresionBooleanaSimple createExpresionBooleanaSimple();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PolePackage getPolePackage();

} //PoleFactory
