/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Suma</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getSuma()
 * @model
 * @generated
 */
public interface Suma extends ExpresionAritmetica
{
} // Suma
