/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.pole;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.pole.Switch#getVar <em>Var</em>}</li>
 *   <li>{@link edu.upb.lp.isc.pole.Switch#getCase <em>Case</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.pole.PolePackage#getSwitch()
 * @model
 * @generated
 */
public interface Switch extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(LlamadoVariable)
   * @see edu.upb.lp.isc.pole.PolePackage#getSwitch_Var()
   * @model containment="true"
   * @generated
   */
  LlamadoVariable getVar();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.pole.Switch#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(LlamadoVariable value);

  /**
   * Returns the value of the '<em><b>Case</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.pole.CaseSwitch}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case</em>' containment reference list.
   * @see edu.upb.lp.isc.pole.PolePackage#getSwitch_Case()
   * @model containment="true"
   * @generated
   */
  EList<CaseSwitch> getCase();

} // Switch
