/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import pole.ui.internal.PoleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PoleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PoleActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PoleActivator activator = PoleActivator.getInstance();
		return activator != null ? activator.getInjector(PoleActivator.EDU_UPB_LP_ISC_POLE) : null;
	}

}
