name: SaludosPole

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.MARCOS_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Gracias por colaborar en el mejor lenguaje de programacion de la historia"
